// app/layout.tsx
import type { Metadata } from "next";
import { Inter, Expletus_Sans, IBM_Plex_Mono } from "next/font/google";
import "../styles/globals.css";
import Navbar from "../components/Navbar";
import ThemeToggle from "../components/ThemeToggle";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const expletus = Expletus_Sans({
  variable: "--font-expletus",
  subsets: ["latin"],
  display: "swap",
});

const plex = IBM_Plex_Mono({
  variable: "--font-plex",
  weight: ["400"], // Required to satisfy TypeScript types
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${expletus.variable} ${plex.variable}`}>
      <body>
        <Navbar />
        <ThemeToggle />
        {children}
      </body>
    </html>
  );
}
